### ISSUE TITLE
Requests rejected for FREE tier

### ISSUE THREAD

**Issue by curtcotner** [joseraul/iex-cloud-api#1]
I only use IEX Cloud one or two days each month.  All of my spread sheets that used to work are getting a VALUE error.   When I run the request below from a browser, I get this response:

https://cloud.iexapis.com/beta/stock/IBM/price?token=

The requested data is not available to free tier accounts. Please upgrade for access to this data.

I recall seeing a post about changes in policy from the data providers.   Did simple things like price quotes get thrown out of the free tier?

**Comment by joseraul** [comment]
I close this, it's very old.
